[package]
name = "tuxphones"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Daemon for Tuxphones BetterDiscord plugin"
homepage = "https://github.com/ImTheSquid/Tuxphones"
repository = "https://github.com/ImTheSquid/Tuxphones"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-binding = "2.26.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ctrlc={ version = "3.2.2", features = ["termination"] }
xcb = { version = "1.1.1", features = ["res"] }