[package]
name = "tuxphones"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Daemon for Tuxphones BetterDiscord plugin"
homepage = "https://github.com/ImTheSquid/Tuxphones"
repository = "https://github.com/ImTheSquid/Tuxphones"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-binding = "2.26.0"
gst = { package = "gstreamer", version = "0.18.0", features = ["v1_20"] }
gst-webrtc = { git="https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", package = "gstreamer-webrtc", features = ["v1_20"] }
gst-sdp = { git="https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", package = "gstreamer-sdp", features = ["v1_20"] }
once_cell = "1.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ctrlc={ version = "3.2.2", features = ["termination"] }
xcb = { version = "1.1.1", features = ["res"] }
sysinfo = "0.24.2"
tracing = "0.1.35"
tracing-subscriber = "0.3.11"
async-tungstenite = {version = "0.17.2", features = ["tokio-native-tls", "tokio-runtime"] }
futures-util = "0.3.21"
regex = "1.5.6"
lazy_static = "1.4.0"
rand = "0.8.5"
image = "0.24.3"
base64 = "0.13.0"
gst-plugin-webrtcredux = {path="../../gst-webrtcredux"}
tokio = "1.20.1"
tokio-native-tls = "0.3.0"