[package]
name = "tuxphones"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Daemon for Tuxphones BetterDiscord plugin"
homepage = "https://github.com/ImTheSquid/Tuxphones"
repository = "https://github.com/ImTheSquid/Tuxphones"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-binding = "2.26.0"
gst = { git="https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", package = "gstreamer" }
gst-webrtc = { git="https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", package = "gstreamer-webrtc" }
gst-sdp = { git="https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", package = "gstreamer-sdp" }
once_cell = "1.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ctrlc={ version = "3.2.2", features = ["termination"] }
xcb = { version = "1.1.1", features = ["res"] }
sysinfo = "0.24.2"
tracing = "0.1.35"
tracing-subscriber = "0.3.11"
tokio = { version = "1.19.2", features = ["full"] }
futures-util = "0.3.21"
tokio-tungstenite = {version = "0.17.1", features = ["rustls-tls-native-roots"] }
reqwest = "0.11.10"